#!/usr/bin/env bash
# Configures an Ngnix server to listen on port 80.

#remove the default Ngnix configuration file
rm /etc/ngnix/sites-enabled/default
# Configure Ngnix to listen on port 80 for all active IPv4 IPs
ln -s /etc/ngnix/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
